### ISSUE TITLE
it can't be build with readme.

### ISSUE THREAD

**Issue by zhushengwen** [julianbuettner/tcp-over-http#6]
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:4:5
   |
4  | /     feature(
5  | |         core_intrinsics,
6  | |         auto_traits,
7  | |         negative_impls,
8  | |         panic_internals,
9  | |         panic_info_message
10 | |     )
   | |_____^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:5:9
  |
5 |         core_intrinsics,
  |         ^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:8:9
  |
8 |         panic_internals,
  |         ^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:9:9
  |
9 |         panic_info_message
  |         ^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `tcp-over-http` due to 4 previous errors

**Comment by julianbuettner** [comment]
Hi there. Thanks for reporting.

Tcp over http currently only works with nightly.
However there was a version working with stable.
I now tagged it as `rocket-stable` and added everything to the Readme.

So you have two options now:  

__1. Go nightly__
```
rustup default nightly
cargo install ... / cargo run ...
```

__2. Stay stable__ 
```
# if cloned repo:
git checkout rocket-stable
cargo run

# or if using cargo install:
cargo install --locked --git https://github.com/julianbuettner/tcp-over-http --tag rocket-stable
```
